---
booktitle: Proceedings of The 1st Transfer Learning for Natural Language Processing
  Workshop
shortname: TL4NLP
volume: '203'
year: '2022'
start: 2022-12-03
end: 2022-12-03
published: 2023-01-19
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: TL4NLP-2022
month: 0
cycles: false
bibtex_editor: Albalak, Alon and Zhou, Chunting and Raffel, Colin and Ramachandran,
  Deepak and Ruder, Sebastian and Ma, Xuezhe
editor:
- given: Alon
  family: Albalak
- given: Chunting
  family: Zhou
- given: Colin
  family: Raffel
- given: Deepak
  family: Ramachandran
- given: Sebastian
  family: Ruder
- given: Xuezhe
  family: Ma
title: Proceedings of Machine Learning Research
description: |
  Proceedings of The 1st Transfer Learning for Natural Language Processing Workshop
    Held in New Orleans, Louisiana, USA on 03 December 2022

  Published as Volume 203 by the Proceedings of Machine Learning Research on 19 January 2023.

  Volume Edited by:
    Alon Albalak
    Chunting Zhou
    Colin Raffel
    Deepak Ramachandran
    Sebastian Ruder
    Xuezhe Ma

  Series Editors:
    Neil D. Lawrence
date_str: 03 Dec
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v203"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v203
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v203
email: ''
conference:
  name: Transfer Learning for Natural Language Processing Workshop
  url: https://tl4nlp.github.io/
  location: New Orleans, Louisiana, USA
  dates:
  - 2022-12-03
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/v203/tl4nlp.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/v203/tl4nlp.bib
